---
title: "1. Data Wrangling"
author: "Solveig Sølverød Mo and Eve Zeyl Fiskebeck"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
    pjs_df: "data/path.xlsx"
    pjs_sheet: "Cleaned_data" 
    vigas_df: "data/path.xlsx"
    source_code: 'code/R'
execute: 
  echo: false
  cache: false
format: html
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
---
<!-- Good to have at hand as comment 
- NVI Rstudio doc : <https://github.com/NorwegianVeterinaryInstitute/posit-team/wiki/Documentation>
- using Renv (allows to work on same versions) <https://rstudio.github.io/renv/articles/renv.html>
- Github repo : <https://github.com/NorwegianVeterinaryInstitute/2025_PAWH_APEC1>


renv::snapshot() # to run when new package installed
renv::load() # is the command to run when the other has updated the script and new packages are installed. 
This is now integrated in the .Rprofile
renv::restore() # to reinstall everything - only if problems
--> 


```{r setup}
library(here)
library(tidyverse)
library(readxl)
library(dplyr)
```





<!-- comment or do not run this if using Rstudio (ask Eve for explanation) -->
```{r params for vscode}
# Only when using VScode (explain)
params <- list()
params$pjs_df <- "data/path.xlsx"
params$pjs_sheet <- "Cleaned_data" 
params$vigas_df <- "data/path.xlsx"
params$source_code <- 'code/R'

params$source_code
here::here(params$source_code)
```


```{r source reused functions}
fun_files_path <- list.files(
  here::here(params$source_code), 
  pattern = "*.R", 
  full.names = TRUE
  )
# sourcing all the functions 
sapply(fun_files_path,source,.GlobalEnv)
```


```{r merge files from VIGAS and PJS}
#Solveig trying to merge files from VIGAS and metadata from PJS:
VIGAS_data <- read_xlsx("data/2025-7-2-APEC_all-All_Fields.xlsx")%>%
  mutate(Year = substr(Sample,1,4))%>%
  filter(Year !="2015")%>%
  filter(Year !="2025")
#removed samples from 2015 and 2025, which should not be included in this study.
PJS_data <- read_xlsx("data/Uttrekk_PJS_010725_SSM.xlsx") 
#799(?) samples to be included in this APEC study. Merge file from VIGAS with file from PJS:
APEC_all_merged <- VIGAS_data %>%
  dplyr::left_join(PJS_data, by = c("Sample"="ID"))
#APEC_all_merged includes data for the 799 included samples.
```

```{r}
#Solveig trying to see how many isolates are missing data from PJS:
missing_PJS_data_artnavn <- APEC_all_merged %>%
  select(`artnavn`) %>%
  group_by(`artnavn`) %>%
  summarise(antall=n())%>%
  arrange(desc(antall))

#3 missing information regarding artnavn.

#check if any are missing hensikt, indicate that data have not been extracted from PJS:
missing_PJS_hensikt <- APEC_all_merged %>%
  select(`hensiktkode`) %>%
  group_by(`hensiktkode`) %>%
  summarise(antall=n())%>%
  arrange(desc(antall))
#None missing hensiktkode after updated PJS uttrekk. Save an output of APEC_all_merged to identify PJS numbers missing hensiktskode:

#write_delim(APEC_all_merged, "data/APEC_all_merged_070525.txt", delim = "\t")
#errors in PJS corrected. Also need to include another "hensikt" in the extraction of data from PJS. Asked Madelaine to fix it. Will run the code again when metadata are updated.
```


```{r}
#Solveig trying to summarize MLST and serotype results:
MLST_count <-APEC_all_merged %>%
  select(`mlst/sequence_type`)%>%
  group_by(`mlst/sequence_type`)%>%
  summarise(antall=n())%>%
  arrange(desc(antall))
#29 missing mlst, should try to run these again, perhaps on SAGA?

serotype_count <- APEC_all_merged %>%
  select(`SeroTypeFinder/SeroType`)%>%
  group_by(`SeroTypeFinder/SeroType`)%>%
  summarise(antall=n())%>%
  arrange(desc(antall))

mlst_and_serotype_count <- APEC_all_merged %>%
  select(`mlst/sequence_type`, `SeroTypeFinder/SeroType`)%>%
  group_by(`SeroTypeFinder/SeroType`, `mlst/sequence_type`)%>%
  summarise(antall=n(), .groups = "drop") %>%
  arrange(desc(antall))
```

```{r}
#Solveig check how many isolates per produsentnr
prodnr_count <-APEC_all_merged %>%
  select(`produsentnr`) %>%
  group_by(`produsentnr`) %>%
  summarise(antall=n()) %>%
  arrange(desc(antall))
#several samples from APEC-Seq missing information regarding produsentnr. Try to fix this in an easy way?
#update July 2025: Information regarding produsentnummer available for all isolates.

#Check how many isolates per saksnr
sak_count <- APEC_all_merged %>%
  select(`sak`) %>%
  group_by(`sak`) %>%
  summarise(antall=n()) %>%
  arrange(desc(antall))

#Check sak per produsentnr
sak_prod_count <- APEC_all_merged %>%
  select(`sak`,`produsentnr`) %>%
  group_by(`produsentnr`, `sak`) %>%
  summarise(antall=n(), .groups ="drop") %>%
  arrange(desc(`produsentnr`))
#cannot get this to work properly - would like it to count number of sak per produsentnummer, but it lists produsentnr and sak and how many isolates are from that one sak. How can we check number of sak per produsent?
```

