<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eve Zeyl Fiskebeck">
<meta name="dcterms.date" content="2026-10-09">

<title>Tidy data verification &amp; visualisation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="TidyData_Visualisation_files/libs/clipboard/clipboard.min.js"></script>
<script src="TidyData_Visualisation_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="TidyData_Visualisation_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="TidyData_Visualisation_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="TidyData_Visualisation_files/libs/quarto-html/popper.min.js"></script>
<script src="TidyData_Visualisation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TidyData_Visualisation_files/libs/quarto-html/anchor.min.js"></script>
<link href="TidyData_Visualisation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TidyData_Visualisation_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TidyData_Visualisation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TidyData_Visualisation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TidyData_Visualisation_files/libs/bootstrap/bootstrap-55aa396ea3e988129bcec43acf404917.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tidy data verification &amp; visualisation</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eve Zeyl Fiskebeck </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Disclaimer:</strong></p>
<p>In this quarto document : - Most of the code has been written by Antrhopic Claude Sonnet - and has been edited and verified by Eve Fiskebeck.</p>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<pre><code>#&gt; here() starts at /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1
#&gt; ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
#&gt; ✔ dplyr     1.1.4     ✔ readr     2.1.5
#&gt; ✔ forcats   1.0.0     ✔ stringr   1.5.1
#&gt; ✔ ggplot2   4.0.3     ✔ tibble    3.2.1
#&gt; ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
#&gt; ✔ purrr     1.0.4     
#&gt; ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
#&gt; ✖ dplyr::filter() masks stats::filter()
#&gt; ✖ dplyr::lag()    masks stats::lag()
#&gt; ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
#&gt; scatterpie v0.2.6 Learn more at https://yulab-smu.top/</code></pre>
</div>
<div class="cell">
<pre><code>#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/add_proportions.R
#&gt; value   ?                                                                                                 
#&gt; visible FALSE                                                                                             
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/check_spelling_homogeneity.R
#&gt; value   ?                                                                                                            
#&gt; visible FALSE                                                                                                        
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/kept_vs_other.R
#&gt; value   ?                                                                                               
#&gt; visible FALSE                                                                                           
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/my_summary_fun.R
#&gt; value   ?                                                                                                
#&gt; visible FALSE                                                                                            
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/summarise_contingency.R
#&gt; value   ?                                                                                                       
#&gt; visible FALSE                                                                                                   
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/top_n_contingency.R
#&gt; value   ?                                                                                                   
#&gt; visible FALSE                                                                                               
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/top_n_other.R
#&gt; value   ?                                                                                             
#&gt; visible FALSE                                                                                         
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/total_distinct_values.R
#&gt; value   ?                                                                                                       
#&gt; visible FALSE                                                                                                   
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/viz/palette_qual.R
#&gt; value   character,8                                                                                        
#&gt; visible FALSE                                                                                              
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/viz/panel_mm_per_data_unit.R
#&gt; value   ?                                                                                                            
#&gt; visible FALSE                                                                                                        
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/viz/save_apec_plot.R
#&gt; value   ?                                                                                                    
#&gt; visible FALSE                                                                                                
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/viz/theme_apec_piematrix.R
#&gt; value   ?                                                                                                          
#&gt; visible FALSE                                                                                                      
#&gt;         /home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/NVI/2025_PAWH_APEC1/code/R/viz/theme_apec.R
#&gt; value   ?                                                                                                
#&gt; visible FALSE</code></pre>
</div>
</section>
<section id="part-1-data-verification-tidy-data" class="level1">
<h1>Part 1: Data verification &amp; tidy data</h1>
<section id="data-import" class="level2">
<h2 class="anchored" data-anchor-id="data-import">1.1 Data import</h2>
<p>Process - Keep only data we will use - then tidy/wrangle data incl.&nbsp;for filtering and verification - kept : <code>Sample</code> for eventual verification and variables for grouping for figures: - <code>ST</code>/<code>Serotype</code> renamed and coerced to character here so nothing downstream touches the raw <code>mlst_scheme_list/sequence_type</code> / <code>SeroTypeFinder/SeroType</code> names. - <code>Production</code> type (driftsformnavn), <code>Species</code> host (artnavn), <code>Year</code> and <code>Case</code> (sak) to be able to know the number of cases registred. - I only used the excel sheet <code>APEC_driftsformsjekk_120226 (2)</code> of the excel file: <code>Results_130226_SSM.xlsx</code> - I had to only keep those columns then for adding to zenodo (remove extra to avoid producent info.)</p>
</section>
<section id="data-verification" class="level2">
<h2 class="anchored" data-anchor-id="data-verification">1.2 Data verification</h2>
<section id="completeness-check" class="level3">
<h3 class="anchored" data-anchor-id="completeness-check">1.2.1 Completeness check:</h3>
<p>One row per isolate, and the fields every downstream figure depends on (year, ST, serotype, production type) must be complete.</p>
<div class="cell">
<pre><code>#&gt; $n_rows
#&gt; [1] 884
#&gt; 
#&gt; $n_distinct_sample
#&gt; [1] 884
#&gt; 
#&gt; $n_missing_year
#&gt; [1] 0
#&gt; 
#&gt; $n_missing_case
#&gt; [1] 0
#&gt; 
#&gt; $n_missing_ST
#&gt; [1] 0
#&gt; 
#&gt; $n_missing_serotype
#&gt; [1] 0
#&gt; 
#&gt; $n_missing_production
#&gt; [1] 0
#&gt; 
#&gt; $n_missing_species
#&gt; [1] 0</code></pre>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="data completeness">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>data completeness
</div>
</div>
<div class="callout-body-container callout-body">
<p>884 rows - and all distinct samples - no missing data</p>
</div>
</div>
</section>
<section id="category-spelling-homogeneity-check" class="level3">
<h3 class="anchored" data-anchor-id="category-spelling-homogeneity-check">1.2.2 Category spelling / homogeneity check</h3>
<p><code>check_spelling_homogeneity()</code> flags pairs of values in a column that are identical after trimming/casefolding (“case_or_whitespace” - safe to auto-fix) or within a small edit distance (“possible_typo” - needs a human read).</p>
<p>Tolerance differs by column: <code>Production</code>/<code>Species</code> are free text, so a 1-2 character difference is almost always a typo (<code>max_dist = 2</code>); <code>ST</code>/ <code>Serotype</code> are nomenclature codes where a 1-character difference is usually a genuinely different code (<code>O1:H4</code> vs.&nbsp;<code>O1:H7</code>), so only exact case/whitespace collisions are flagged (<code>max_dist = 0</code>). Moreover those should be automatically assigned so it should not be any errors</p>
<div class="cell">
<pre><code>#&gt; # A tibble: 2 × 5
#&gt;   column     value_a                      value_b                 distance flag 
#&gt;   &lt;chr&gt;      &lt;chr&gt;                        &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;
#&gt; 1 Production Foreldredyr, kjøttproduksjon Foreldredyr, kj�ttprod…        1 poss…
#&gt; 2 Species    Rowan ranger                 Rowan Ranger                   0 case…</code></pre>
</div>
<ul>
<li><p>problems reading norwegian special characters - got corrupted sometimes &gt; This is why data usually does not use special characters - this simplifies the work.</p></li>
<li><p>fixed below: <code>Production</code> has a known mojibake artifact (“Foreldredyr, kjøttproduksjon” vs.&nbsp;corrupted “Foreldredyr, kj�ttproduksjon”, 2 rows)</p></li>
<li><p><code>Species</code> has one genuine case duplicate (“Rowan ranger” vs.&nbsp;“Rowan Ranger”</p></li>
<li><p>the other near-neighbours are real, distinct breed names and are correctly not flagged)</p></li>
<li><p><code>ST</code>/<code>Serotype</code> have nothing flagged. (expected given code ! - Trivial)</p></li>
</ul>
<p>Manual verification</p>
<div class="callout callout-style-default callout-important callout-titled" title="Asked questions / decisions (Solveig)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Asked questions / decisions (Solveig)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>ONT and HNT kept as is - same for the multiple serotypes with /- see bellow for Species grouping - also decided (Solveig)</li>
</ul>
<p><strong>Categories species grouping/renaming:</strong> - “Hubbard JA 787” as “Hubbard” - “Ross” as “Ross 308”</p>
</div>
</div>
</section>
</section>
<section id="cleaning-production-type-broiler-parent-flock" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-production-type-broiler-parent-flock">1.4 Cleaning: production type (broiler / parent flock)</h2>
<p>And transforming Norwegian to English</p>
<div class="cell">
<pre><code>#&gt; # A tibble: 2 × 2
#&gt;   production_type     n
#&gt;   &lt;fct&gt;           &lt;int&gt;
#&gt; 1 Broiler           650
#&gt; 2 Parent            234
#&gt; # A tibble: 8 × 2
#&gt;   Species          n
#&gt;   &lt;fct&gt;        &lt;int&gt;
#&gt; 1 Chicken         77
#&gt; 2 Ross 308       647
#&gt; 3 Hubbard        140
#&gt; 4 Ross rowan       3
#&gt; 5 Rowan 308        1
#&gt; 6 Rowan ranger     9
#&gt; 7 Rustic gold      2
#&gt; 8 Sasso            5</code></pre>
</div>
</section>
<section id="new-variable-variant-st-serotype-combination" class="level2">
<h2 class="anchored" data-anchor-id="new-variable-variant-st-serotype-combination">1.5 New variable: <code>variant</code> (ST-Serotype combination)</h2>
<p>Requested format: <code>ST23-O78:H4</code>.</p>
<div class="cell">
<pre><code>#&gt; [1] 134
#&gt; # A tibble: 5 × 2
#&gt;   variant             n
#&gt;   &lt;chr&gt;           &lt;int&gt;
#&gt; 1 ST23-O78:H4       244
#&gt; 2 ST429-O2/O50:H1    53
#&gt; 3 ST131-O25:H4       46
#&gt; 4 ST117-O24:H4       38
#&gt; 5 ST95-O2/O50:H5     36</code></pre>
</div>
</section>
<section id="st-serotype-variant-contingency-tables-evaluation---top-5-top-10" class="level2">
<h2 class="anchored" data-anchor-id="st-serotype-variant-contingency-tables-evaluation---top-5-top-10">1.6 ST, Serotype, variant contingency tables evaluation - top 5 / top 10</h2>
<blockquote class="blockquote">
<p>preparation for data visualisation:</p>
</blockquote>
<p>Same question, two groupings: - keep the top N <em>variants</em>, how many distinct ST/Serotype does that represent - keep the top N <em>ST</em>s instead, how many distinct Serotype/variant.</p>
<p>Same <code>top_n_contingency()</code> pattern for both, just a different <code>group_col</code> / <code>other_cols</code> - shared helpers (<code>kept_vs_other()</code>, <code>total_distinct_values()</code>, <code>add_proportions()</code>, all in <code>code/R/</code>)</p>
<div class="cell">
<pre><code>#&gt; # A tibble: 3 × 2
#&gt;   other_col n_total_distinct
#&gt;   &lt;chr&gt;                &lt;int&gt;
#&gt; 1 ST                      88
#&gt; 2 Serotype               115
#&gt; 3 variant                134</code></pre>
</div>
<section id="grouped-by-variant" class="level3">
<h3 class="anchored" data-anchor-id="grouped-by-variant">Grouped by variant</h3>
<blockquote class="blockquote">
<p>to see at which level we need to group for the figures</p>
</blockquote>
<div class="cell">
<pre><code>#&gt; # A tibble: 8 × 7
#&gt;   top_n other_col group_value n_isolates pct_isolates n_distinct_values
#&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;            &lt;int&gt;        &lt;dbl&gt;             &lt;int&gt;
#&gt; 1     5 ST        kept               417         47.2                 5
#&gt; 2     5 Serotype  kept               417         47.2                 5
#&gt; 3     5 ST        other              467         52.8                86
#&gt; 4     5 Serotype  other              467         52.8               114
#&gt; 5    10 ST        kept               550         62.2                 8
#&gt; 6    10 Serotype  kept               550         62.2                10
#&gt; 7    10 ST        other              334         37.8                83
#&gt; 8    10 Serotype  other              334         37.8               110
#&gt; # ℹ 1 more variable: pct_distinct_values &lt;dbl&gt;</code></pre>
</div>
<ul>
<li><p>keeping the top 5 variants covers 417/884 isolates (47.2%) but names only 5/88 STs (5.7%) and 5/115 serotypes (4.3%) - the “other” bucket is the minority of isolates (467, 52.8%) yet holds nearly all of the diversity (97.7% of STs, 99.1% of serotypes).</p></li>
<li><p>Top 10 covers more isolates (550/884, 62.2%) at a similar diversity trade-off - 8 STs (9.1%) and 10 serotypes (8.7%) named, 94.3%/95.7% still in “other”. Neither threshold captures much ST/Serotype diversity - that’s inherent to a “top N” cut on data this skewed (one variant, ST23-O78:H4, is 244/884 isolates - 27.6% - on its own), not a flaw in the threshold choice.</p></li>
</ul>
</section>
<section id="grouped-by-st" class="level3">
<h3 class="anchored" data-anchor-id="grouped-by-st">Grouped by ST</h3>
<div class="cell">
<pre><code>#&gt; # A tibble: 8 × 7
#&gt;   top_n other_col group_value n_isolates pct_isolates n_distinct_values
#&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;            &lt;int&gt;        &lt;dbl&gt;             &lt;int&gt;
#&gt; 1     5 Serotype  kept               505         57.1                18
#&gt; 2     5 variant   kept               505         57.1                19
#&gt; 3     5 Serotype  other              379         42.9               103
#&gt; 4     5 variant   other              379         42.9               115
#&gt; 5    10 Serotype  kept               645         73                  23
#&gt; 6    10 variant   kept               645         73                  25
#&gt; 7    10 Serotype  other              239         27                  98
#&gt; 8    10 variant   other              239         27                 109
#&gt; # ℹ 1 more variable: pct_distinct_values &lt;dbl&gt;</code></pre>
</div>
<p>Grouping by ST instead captures more diversity per isolate, because one ST can carry several different serotypes. - Top 5 STs cover 505/884 isolates (57.1%) and represent 18/115 serotypes (15.7%) and 19/134 variants (14.2%) - roughly 3-4x the serotype/variant coverage of the top-5 <em>variant</em> grouping, for a similar isolate share. “Other” (379 isolates, 42.9%) still holds most of the diversity (103 serotypes, 89.6%; 115 variants, 85.8%).</p>
<ul>
<li>Top 10 STs: 645/884 isolates (73.0%), 23 serotypes (20.0%), 25 variants (18.7%) named; 239 other isolates (27.0%) still cover 98 serotypes (85.2%) and 109 variants (81.3%).</li>
</ul>
</section>
</section>
<section id="preparing-for-figures" class="level2">
<h2 class="anchored" data-anchor-id="preparing-for-figures">Preparing for figures</h2>
<section id="scatter-pie-chart--top-10-variants-choosen." class="level3">
<h3 class="anchored" data-anchor-id="scatter-pie-chart--top-10-variants-choosen.">1. Scatter pie chart- top 10 variants choosen.</h3>
<p>Top 10 ST-Serotype variants by isolate count, “Other” grouping everything else.</p>
<div class="cell">
<pre><code>#&gt; # A tibble: 78 × 4
#&gt; # Groups:   Year, variant_top10 [54]
#&gt;     Year variant_top10   production_type     n
#&gt;    &lt;int&gt; &lt;chr&gt;           &lt;fct&gt;           &lt;int&gt;
#&gt;  1  2018 Other           Broiler            13
#&gt;  2  2018 Other           Parent              3
#&gt;  3  2018 ST117-O161:H4   Broiler             1
#&gt;  4  2018 ST429-O2/O50:H1 Broiler            14
#&gt;  5  2018 ST95-O1:H7      Parent              2
#&gt;  6  2019 Other           Broiler            20
#&gt;  7  2019 Other           Parent             10
#&gt;  8  2019 ST131-O25:H4    Parent              1
#&gt;  9  2019 ST371-O45:H19   Broiler             5
#&gt; 10  2019 ST429-O2/O50:H1 Broiler            37
#&gt; # ℹ 68 more rows</code></pre>
</div>
<div class="cell">
<pre><code>#&gt; # A tibble: 54 × 7
#&gt; # Groups:   Year, variant_top10 [54]
#&gt;     Year variant_top10   Broiler Parent     x     y total
#&gt;    &lt;int&gt; &lt;fct&gt;             &lt;int&gt;  &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
#&gt;  1  2018 Other                13      3  18.7  2018    16
#&gt;  2  2018 ST117-O161:H4         1      0  10.2  2018     1
#&gt;  3  2018 ST429-O2/O50:H1      14      0   3.4  2018    14
#&gt;  4  2018 ST95-O1:H7            0      2  11.9  2018     2
#&gt;  5  2019 Other                20     10  18.7  2019    30
#&gt;  6  2019 ST131-O25:H4          0      1   5.1  2019     1
#&gt;  7  2019 ST371-O45:H19         5      0  13.6  2019     5
#&gt;  8  2019 ST429-O2/O50:H1      37      0   3.4  2019    37
#&gt;  9  2019 ST95-O1:H7            4     17  11.9  2019    21
#&gt; 10  2019 ST95-O2/O50:H5        8      2   8.5  2019    10
#&gt; # ℹ 44 more rows</code></pre>
</div>
<p>Pie size uses 4 fixed categories (1-10, 10-50, 50-100, 100-200 isolates) instead of a continuous scale, so sizes are easy to compare at a glance. Each category gets one area-corrected radius (sqrt, not linear - a linear radius would make circle area, which is what a reader actually perceives, grow with the square of the count and exaggerate differences).</p>
<div class="cell">
<pre><code>#&gt; # A tibble: 54 × 9
#&gt; # Groups:   Year, variant_top10 [54]
#&gt;     Year variant_top10   Broiler Parent     x     y total total_bin      r
#&gt;    &lt;int&gt; &lt;fct&gt;             &lt;int&gt;  &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;fct&gt;      &lt;dbl&gt;
#&gt;  1  2018 Other                13      3  18.7  2018    16 10-50     0.21  
#&gt;  2  2018 ST117-O161:H4         1      0  10.2  2018     1 1-10      0.0939
#&gt;  3  2018 ST429-O2/O50:H1      14      0   3.4  2018    14 10-50     0.21  
#&gt;  4  2018 ST95-O1:H7            0      2  11.9  2018     2 1-10      0.0939
#&gt;  5  2019 Other                20     10  18.7  2019    30 10-50     0.21  
#&gt;  6  2019 ST131-O25:H4          0      1   5.1  2019     1 1-10      0.0939
#&gt;  7  2019 ST371-O45:H19         5      0  13.6  2019     5 1-10      0.0939
#&gt;  8  2019 ST429-O2/O50:H1      37      0   3.4  2019    37 10-50     0.21  
#&gt;  9  2019 ST95-O1:H7            4     17  11.9  2019    21 10-50     0.21  
#&gt; 10  2019 ST95-O2/O50:H5        8      2   8.5  2019    10 10-50     0.21  
#&gt; # ℹ 44 more rows</code></pre>
</div>
<p>r = 0.42 * sqrt(bin_upper / 200) - sqrt keeps circle <em>area</em> (not radius) proportional to isolate count; 0.42 is chosen so the biggest category’s circle fits one grid cell without touching its neighbours.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TidyData_Visualisation_files/figure-html/figure7%20top10%20pie-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sampling-distribution-isolates-per-year-by-production-type" class="level3">
<h3 class="anchored" data-anchor-id="sampling-distribution-isolates-per-year-by-production-type">Sampling distribution: isolates per year by production type</h3>
<p>Sampling overview: total isolates collected per year, split by production type.</p>
<div class="cell">
<pre><code>#&gt; # A tibble: 16 × 3
#&gt; # Groups:   Year [8]
#&gt;     Year production_type     n
#&gt;    &lt;int&gt; &lt;fct&gt;           &lt;int&gt;
#&gt;  1  2018 Broiler            28
#&gt;  2  2018 Parent              5
#&gt;  3  2019 Broiler            74
#&gt;  4  2019 Parent             30
#&gt;  5  2020 Broiler            71
#&gt;  6  2020 Parent             14
#&gt;  7  2021 Broiler           270
#&gt;  8  2021 Parent             47
#&gt;  9  2022 Broiler            83
#&gt; 10  2022 Parent             22
#&gt; 11  2023 Broiler            33
#&gt; 12  2023 Parent             17
#&gt; 13  2024 Broiler            30
#&gt; 14  2024 Parent             45
#&gt; 15  2025 Broiler            61
#&gt; 16  2025 Parent             54</code></pre>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TidyData_Visualisation_files/figure-html/figure9%20sampling%20design%20bar-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="reproducibility" class="level1">
<h1>Reproducibility</h1>
<p>R version and exact package versions used to produce this document - written to <code>code/sessionInfo.txt</code> as well as printed below, so it travels with the code itself (not just <code>renv.lock</code>, which lives outside <code>code/</code>).</p>
<div class="cell">
<pre><code>#&gt; R version 4.5.3 (2026-03-11)
#&gt; Platform: x86_64-redhat-linux-gnu
#&gt; Running under: Fedora Linux 43 (KDE Plasma Desktop Edition)
#&gt; 
#&gt; Matrix products: default
#&gt; BLAS/LAPACK: FlexiBLAS OPENBLAS-OPENMP;  LAPACK version 3.12.1
#&gt; 
#&gt; locale:
#&gt;  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#&gt;  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#&gt;  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#&gt;  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#&gt;  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#&gt; [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#&gt; 
#&gt; time zone: Europe/Oslo
#&gt; tzcode source: system (glibc)
#&gt; 
#&gt; attached base packages:
#&gt; [1] stats     graphics  grDevices datasets  utils     methods   base     
#&gt; 
#&gt; other attached packages:
#&gt;  [1] scatterpie_0.2.6 readxl_1.4.5     lubridate_1.9.4  forcats_1.0.0   
#&gt;  [5] stringr_1.5.1    dplyr_1.1.4      purrr_1.0.4      readr_2.1.5     
#&gt;  [9] tidyr_1.3.1      tibble_3.2.1     ggplot2_4.0.3    tidyverse_2.0.0 
#&gt; [13] here_1.0.1      
#&gt; 
#&gt; loaded via a namespace (and not attached):
#&gt;  [1] yulab.utils_0.2.5  utf8_1.2.4         rappdirs_0.3.3     generics_0.1.3    
#&gt;  [5] renv_1.0.7         stringi_1.8.4      hms_1.1.3          digest_0.6.37     
#&gt;  [9] magrittr_2.0.3     evaluate_1.0.5     grid_4.5.3         timechange_0.3.0  
#&gt; [13] RColorBrewer_1.1-3 fastmap_1.2.0      cellranger_1.1.0   rprojroot_2.0.4   
#&gt; [17] jsonlite_2.0.0     scales_1.4.0       tweenr_2.0.3       textshaping_1.0.0 
#&gt; [21] cli_3.6.6          crayon_1.5.3       rlang_1.3.0        polyclip_1.10-7   
#&gt; [25] bit64_4.6.0-1      withr_3.0.2        yaml_2.3.10        parallel_4.5.3    
#&gt; [29] tools_4.5.3        tzdb_0.5.0         vctrs_0.6.5        R6_2.6.1          
#&gt; [33] lifecycle_1.0.4    bit_4.6.0          fs_1.6.5           ggfun_0.2.1       
#&gt; [37] vroom_1.6.5        MASS_7.3-64        ragg_1.3.3         pkgconfig_2.0.3   
#&gt; [41] pillar_1.10.1      gtable_0.3.6       glue_1.8.0         systemfonts_1.2.1 
#&gt; [45] ggforce_0.5.0      xfun_0.60          tidyselect_1.2.1   knitr_1.50        
#&gt; [49] farver_2.1.2       htmltools_0.5.8.1  labeling_0.4.3     rmarkdown_2.29    
#&gt; [53] compiler_4.5.3     S7_0.2.2</code></pre>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>